apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-apps
  namespace: argocd
spec:
  generators:
    - directory:
        path: apps/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

      source:
        repoURL: https://github.com/jpohell/k8s-lab-gitrepo.git
        targetRevision: main
        path: apps/{{path.basename}}
        helm:
          valueFiles:
            - values.yaml

  templatePatch: |
    {{- if eq path.basename "longhorn" }}
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: longhorn-system
      source:
        repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: 1.6.2
        helm:
          valueFiles:
            - apps/longhorn/values.yaml
    {{- end }}
