apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jpohell/k8s-lab-gitrepo.git
        revision: main
        directories:
          - path: apps/*/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jpohell/k8s-lab-gitrepo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
