apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
    createNamespace: true
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.2
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
