ingress:
  enabled: true
  host: longhorn.local
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: false

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  backupTarget: ""
  backupTargetCredentialSecret: ""
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 3
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  guaranteedEngineManagerCPU: 0
  guaranteedReplicaManagerCPU: 0

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
