apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jpohell/k8s-lab-gitrepo.git
    targetRevision: main
    path: apps/harbor
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
