adminUser: admin
adminPassword: "Grafana12345"

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.local
  tls: []

persistence:
  enabled: true
  type: pvc
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default: {}
